In [42]:
#libraries

import numpy as np
from preprocessing import build_lin_com3, build_lin_com, build_sqrt, build_lin_com_deg, build_poly, build_all_deg_3, build_hyperb
from preprocessing import build_data
#Useful tools
%matplotlib inline
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [56]:
#Generation of a data set (in order to check our fonctions)

N = 7 #nb of datas
M = 4 #nb of features

tx = np.zeros((N,M))

for k in range(N):
    tx[k] = [s+1 for s in range(M)]
    
tx

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [4]:
###############################################################################
#=============================================================================
#============ TEST OF BUILD LIN COM3 ========================================
#==========================================================================
#########################################################################3333

t2 = build_lin_com(tx)

t3 = build_lin_com3(tx)

print(t3)

[[6.]
 [6.]
 [6.]
 [6.]
 [6.]
 [6.]
 [6.]]


In [6]:
###############################################################################
#=============================================================================
#============ TEST OF BUILD LIN COM DEG  ========================================
#==========================================================================
#########################################################################3333

t4 = build_lin_com_deg(tx,2)

t4

array([[ 2.,  3.,  4., 12.,  9., 18.],
       [ 2.,  3.,  4., 12.,  9., 18.],
       [ 2.,  3.,  4., 12.,  9., 18.],
       [ 2.,  3.,  4., 12.,  9., 18.],
       [ 2.,  3.,  4., 12.,  9., 18.],
       [ 2.,  3.,  4., 12.,  9., 18.],
       [ 2.,  3.,  4., 12.,  9., 18.]])

In [7]:
###############################################################################
#=============================================================================
#============ TEST OF BUILD ALL DEG 3  ========================================
#==========================================================================
#########################################################################3333


t4 = build_all_deg_3(tx)

t4

array([[ 6.,  2.,  3.,  4., 12.,  9., 18.],
       [ 6.,  2.,  3.,  4., 12.,  9., 18.],
       [ 6.,  2.,  3.,  4., 12.,  9., 18.],
       [ 6.,  2.,  3.,  4., 12.,  9., 18.],
       [ 6.,  2.,  3.,  4., 12.,  9., 18.],
       [ 6.,  2.,  3.,  4., 12.,  9., 18.],
       [ 6.,  2.,  3.,  4., 12.,  9., 18.]])

In [29]:
#test for indices

n= 5
for i in np.arange(n-2):
    bubu = 0
    #col = tx[:,i]
    #print("i+1 = ", i+1, "n = ", n) #Note : the order matters
    #print(tx[:,i+1:n])
    #out = np.c_[out, to_add]
    
          
          
#for i in np.arange(n-2):
#    col = tx[:,i]
#    to_add = build_lin_com2( tx[:,i+1:n-1] ) * col[:, np.newaxis] #Note : the order matters
#    out = np.c_[out, to_add]

In [30]:
tx
x = tx[:,0]
y = 2*x
tx*y[:,np.newaxis]

tx**2

array([[ 1.,  4.,  9., 16., 25.],
       [ 1.,  4.,  9., 16., 25.],
       [ 1.,  4.,  9., 16., 25.],
       [ 1.,  4.,  9., 16., 25.],
       [ 1.,  4.,  9., 16., 25.],
       [ 1.,  4.,  9., 16., 25.],
       [ 1.,  4.,  9., 16., 25.]])

In [74]:
deg = 2

n = tx.shape[1]
out = np.ones((tx.shape[0],1))
#print(out)

for i in np.arange(n-2):
    col = tx[:,i]
    pol_deg = build_poly(tx[:,i+1:n],deg)
    to_add = pol_deg*col[:, np.newaxis]
    out = np.c_[out, to_add]

last = tx[:,tx.shape[1]-1]**deg * tx[:,tx.shape[1]-2]
out = np.c_[out,last]
out

array([[  1.,   4.,   9.,  16.,  25.,  18.,  32.,  50.,  48.,  75., 100.],
       [  1.,   4.,   9.,  16.,  25.,  18.,  32.,  50.,  48.,  75., 100.],
       [  1.,   4.,   9.,  16.,  25.,  18.,  32.,  50.,  48.,  75., 100.],
       [  1.,   4.,   9.,  16.,  25.,  18.,  32.,  50.,  48.,  75., 100.],
       [  1.,   4.,   9.,  16.,  25.,  18.,  32.,  50.,  48.,  75., 100.],
       [  1.,   4.,   9.,  16.,  25.,  18.,  32.,  50.,  48.,  75., 100.],
       [  1.,   4.,   9.,  16.,  25.,  18.,  32.,  50.,  48.,  75., 100.]])

In [23]:
tx
ty = tx
np.cosh(ty)

array([[1.54308063, 3.76219569],
       [1.54308063, 3.76219569],
       [1.54308063, 3.76219569],
       [1.54308063, 3.76219569],
       [1.54308063, 3.76219569],
       [1.54308063, 3.76219569],
       [1.54308063, 3.76219569]])

In [57]:
tz = build_data(tx, comb3= 1)

tz

array([[ 6.,  8., 12., 24.,  2.,  3.,  4.,  4., 12., 16.,  9., 18., 36.,
        16., 32., 48.],
       [ 6.,  8., 12., 24.,  2.,  3.,  4.,  4., 12., 16.,  9., 18., 36.,
        16., 32., 48.],
       [ 6.,  8., 12., 24.,  2.,  3.,  4.,  4., 12., 16.,  9., 18., 36.,
        16., 32., 48.],
       [ 6.,  8., 12., 24.,  2.,  3.,  4.,  4., 12., 16.,  9., 18., 36.,
        16., 32., 48.],
       [ 6.,  8., 12., 24.,  2.,  3.,  4.,  4., 12., 16.,  9., 18., 36.,
        16., 32., 48.],
       [ 6.,  8., 12., 24.,  2.,  3.,  4.,  4., 12., 16.,  9., 18., 36.,
        16., 32., 48.],
       [ 6.,  8., 12., 24.,  2.,  3.,  4.,  4., 12., 16.,  9., 18., 36.,
        16., 32., 48.]])

In [36]:
ty = (-tx + 2)*2
tz = np.where(ty < 0, -np.sqrt( np.abs(ty) ), np.sqrt(np.abs(ty)))

array([[ 1.41421356,  0.        , -1.41421356, -2.        ],
       [ 1.41421356,  0.        , -1.41421356, -2.        ],
       [ 1.41421356,  0.        , -1.41421356, -2.        ],
       [ 1.41421356,  0.        , -1.41421356, -2.        ],
       [ 1.41421356,  0.        , -1.41421356, -2.        ],
       [ 1.41421356,  0.        , -1.41421356, -2.        ],
       [ 1.41421356,  0.        , -1.41421356, -2.        ]])

In [32]:
- np.sqrt( np.abs(ty))

array([[-1.41421356, -0.        , -1.41421356, -2.        ],
       [-1.41421356, -0.        , -1.41421356, -2.        ],
       [-1.41421356, -0.        , -1.41421356, -2.        ],
       [-1.41421356, -0.        , -1.41421356, -2.        ],
       [-1.41421356, -0.        , -1.41421356, -2.        ],
       [-1.41421356, -0.        , -1.41421356, -2.        ],
       [-1.41421356, -0.        , -1.41421356, -2.        ]])