In [11]:
#libraries

import numpy as np
from implementations import *

#Useful tools
%matplotlib inline
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [3]:
#Generation of a data set (in order to check our fonctions)

N = 60 #nb of datas
M = 5 #nb of features

y = np.zeros(N)
tx = np.zeros((N,M))

a,b = int(-N/2), int(N/2)

for k in range(a,b):
    #points measures with normal distributed noise
    #noise on both measures tx and y
    y[k] = 0.5 * k**4 + 2*k**2 - 8 + 3*np.random.randn()
    tx[k] = [k**i for i in range(M)] + 0.1*np.random.randn(M)
    

In [206]:
#Test of least_squares_GD : il est bon pour les grands degrees mais pas le reste

w_init = np.ones(M)
w_init = [10 for _ in range(M)]
max_iters = 10000000
gamma = 0.00000000001

w_LSGD, loss_LSGD = least_squares_GD(y, tx, w_init, max_iters, gamma)

w_LSGD


array([ 9.96914278,  9.95904049,  4.08007956, -0.01785012,  0.49696254])

In [202]:
#Test of least_squares_GD : il est bon pour les grands degrees mais pas le reste
#second test (without the minus)
#ok ca diverge (j'ai rien dit)

w_init = np.ones(M)
w_init = [10 for _ in range(M)]
max_iters = 10000000
gamma = 0.00000000001

w_LSGD, loss_LSGD = least_squares_GD(y, tx, w_init, max_iters, gamma)

w_LSGD


array([nan, nan, nan, nan, nan])

In [217]:
#Test of least_squares : il fonctionne très bien
w_LS, loss_LS = least_squares(y, tx)

w_LS

array([-7.31425783e+00,  1.64637385e-02,  1.99263335e+00, -4.44458146e-06,
        5.00007877e-01])

In [190]:
#Test of least_squares_SGD : il est bon pour les grands degrees mais pas le reste
#Note : Faut faire plus d'itérations qu'avec GD et prendre un gamma plus petit

w_init = [10 for _ in range(M)]
max_iters = 1000000
gamma = 0.000000000001

w_LS_SGD, loss_LS_SGD = least_squares_SGD(y, tx, w_init, max_iters, gamma)
w_LS_SGD

array([ 9.99940254,  9.98432228,  9.87076257, -0.02441925,  0.48904404])

In [196]:
#Test batch_iter : C'est juste pour montrer que de base, on prend qu'un seul 
#                  point à chaque fois ! donc faut vraiment bcp d'itérations
#                  pour que ca converge
max_iters = 5

for n_iter in range(max_iters):
    for y_batch, tx_batch in batch_iter(y, tx, batch_size=1, num_batches=1):
        print(y_batch)      

[352.26566529]
[352.97501283]
[1290.82825213]
[3436.17327723]
[229837.83697349]


In [4]:
##################################################################################################################
##################################################################################################################
##################################################################################################################

#Test Ridge_regression 
#Globalement ca marche bien, le vrai souci, c'est que s'il y a une dépendance
#constante (comme ici), elle est presque automatiquement détruite car elle a peu
#d'influence sur les grandes valeurs

lambda_ = 1
w_RR, loss_RR = ridge_regression(y, tx, lambda_)

w_RR

array([-9.78201210e-01,  1.01187972e-02,  1.96031584e+00, -6.39111201e-05,
        5.00041726e-01])

In [7]:
#Test Ridge Regression with Gradient Descent !
#Watch out of the types !
#Our functions only works with 'np.array' !
# 2 * [1,2,3] = [2,4,6] if type = 'np.array' 
# 2 * [1,2,3] = [1,2,3,1,2,3] if type = 'list'

#C'est comme Least Square with Gradient Descent et on pénalise encore plus
#les petits polynomes car on a un régulateur !


w_init = np.array([10 for _ in range(M)])
max_iters = 1000000
gamma = 0.000000000001
lambda_ = 1

w_RR_GD, loss_RR_GD = ridge_GD(y, tx, w_init, max_iters, gamma,lambda_)
w_RR_GD

array([ 9.99936157,  9.98422825,  9.86965421, -0.02449436,  0.48868362])

In [17]:
#Test Logistic_regression
#j'ai un souci ?

w_init = np.array([10 for _ in range(M)])
max_iters = 10
gamma = 0.000000001

w_LR, loss_LR = logistic_regression(y, tx, w_init, max_iters, gamma)

C:\Users\etaxi\Desktop\ALL\MASTER1_COURS\GitHub\MachineLearningProject1\implementations.py:169: RuntimeWarning: divide by zero encountered in log
  


In [19]:
#Test reg_logistic_regression
#j'ai un souci ?

w_init = np.array([10 for _ in range(M)])
max_iters = 10
gamma = 0.000000001
Lambda_ = 1

w_RLR, loss_RLR = reg_logistic_regression(y, tx, lambda_, w_init, max_iters, gamma)

C:\Users\etaxi\Desktop\ALL\MASTER1_COURS\GitHub\MachineLearningProject1\implementations.py:170: RuntimeWarning: divide by zero encountered in log
  return loss
